version: "3.8"

services:
  django:
    image: zotterstrom/django-image:10
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=0 # Set appropriate environment variables for production
    # Removed volumes for SQLite and local paths - consider using a managed database like RDS

  angular:
    image: zotterstrom/angular-image:third
    # Angular build files are served by Nginx, so this service doesn't need to expose ports directly to the host

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Expose Nginx on port 80 of the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Map your Nginx configuration file into the container
      - static_volume:/app/static # Static files volume
      - media_volume:/app/media # Media files volume
    depends_on:
      - django
      - angular

volumes:
  static_volume:
  media_volume:
