version: '3.8'

services:
  django:
    image: zotterstrom/django-image:first
    volumes:
      - ./back_end:/back_end # Map your Django project into the container
      - ./back_end/db.sqlite3:/app/db.sqlite3 # Ensure SQLite database file is persisted
      - static_volume:/app/static # Persist Django static files
      - media_volume:/app/media # Persist Django media files
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 # Set to 0 in production
    command: python manage.py runserver 0.0.0.0:8000

  angular:
    image: zotterstrom/angular-image:first
    ports:
      - "4200:80"

volumes:
  static_volume:
  media_volume:


