//<-- payment.model.ts -->
export class Payment {
    // id: number;                   // A unique identifier for the payment (db pkey)
    leaseHolderFirstName: string;
    leaseHolderLastName: string;
    leaseHolderId: number;        // The ID of the associated with the lease holder (db foreign key)
    amount: number;               // Amount paid
    datePaid: Date;               // Date of the payment
    dueDate: Date;                // Date the payment was due
    lateFeeApplied: boolean;      // Whether a late fee was applied to this payment

    constructor(
        //    id?: number, // '?' makes it optional, indicating the frontend won't be providing this and it's expected to be generated by the backend
        leaseHolderFirstName: string,
        leaseHolderLastName: string,
        leaseHolderId: number,
        amount: number,
        datePaid: Date,
        dueDate: Date,
        lateFeeApplied: boolean = false
    ) {
        // this.id = id;
        this.leaseHolderFirstName = leaseHolderFirstName;
        this.leaseHolderLastName = leaseHolderLastName;
        this.leaseHolderId = leaseHolderId;
        this.amount = amount;
        this.datePaid = datePaid;
        this.dueDate = dueDate;
        this.lateFeeApplied = lateFeeApplied;
    }
}
