# Generated by Django 4.2.6 on 2023-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_holder_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lot_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leaseholder',
            name='lease_holder_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_number',
            field=models.IntegerField(),
        ),
    ]
