# Generated by Django 4.2.6 on 2024-01-07 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of the most recent payment', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='last_payment_date_id',
            field=models.ForeignKey(blank=True, help_text='ID of the most recent payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_payment_for_lease', to='lots.payment'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='payment_status',
            field=models.CharField(choices=[('up-to-date', 'Up to date'), ('Late', 'Late'), ('delinquent', 'Delinquent')], default='Late', max_length=20),
        ),
    ]
