# Generated by Django 4.2.6 on 2023-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='monthly_rental_amount',
            field=models.IntegerField(),
        ),
    ]
