# Generated by Django 4.2.6 on 2023-10-24 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_alter_lease_monthly_rental_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseholder',
            old_name='lease_holder_name',
            new_name='lease_holder_first_name',
        ),
        migrations.AddField(
            model_name='leaseholder',
            name='lease_holder_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
