# Generated by Django 4.2.6 on 2023-10-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_rename_lease_holder_name_leaseholder_lease_holder_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseholder',
            old_name='lease_address',
            new_name='lease_holder_address',
        ),
    ]
