# Generated by Django 4.2.6 on 2023-10-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_rename_lease_address_leaseholder_lease_holder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lots.leaseholder'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Date of payment')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer')], help_text='Method of payment', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID if available', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or information about the payment', null=True)),
                ('receipt', models.FileField(blank=True, help_text='Scanned image or PDF of the payment receipt', null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the payment record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag to mark record as deleted without actually removing it')),
                ('lease', models.ForeignKey(help_text='The lease the payment is for', on_delete=django.db.models.deletion.CASCADE, to='lots.lease')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_date'], name='lots_paymen_payment_de74a7_idx')],
            },
        ),
    ]
