# Generated by Django 4.2.7 on 2023-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_alter_lease_lease_holder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
